### ISSUE TITLE
Multiple Debug Verbosity Levels

### ISSUE THREAD

**Issue by badavis** [everyone-counts/mongo-stream#20]
Logging needs to be standardized and configurable for multiple verbosity levels. 

We should convert all console.log() statement to debug() using https://www.npmjs.com/package/debug

**Comment by AndrewVDP** [comment]
Do you think we should convert it to use service-logger instead?
https://github.com/giancarlocosta/service-logger

**Comment by lordjabez** [comment]
Man, who's the genius who wrote that bit of code? :)

We can move it over to our organization page, then merge it in.

@giancarlocosta, is `service-logger` published in public `npm` ?

**Comment by giancarlocosta** [comment]
Indeed: https://www.npmjs.com/package/service-logger

**Comment by badavis** [comment]
Perfect, didn't know it was already open-sourced
