### ISSUE TITLE
Custom mappings being ignored

### ISSUE THREAD

**Issue by chrishearn** [everyone-counts/mongo-stream#40]
I've experienced a problem with getting custom mappings working, but did manage to find a solution.

I noticed initially that the master branch was not accepting mappings from the config file, so I cloned the repo and merged PR #38 into a new branch, however my custom mappings were still not working and upon further investigation I found they were still being overridden by the "default" mapping setting. 

I had to comment out `this.elasticManager.setMappings(collection);` in the constructor of CollectionManager which fixed the issue. This line seems to be resetting the custom mappings.

Thought I'd make you aware - thanks for the great work on this project!

**Comment by g2valdez** [comment]
Can I ask for some more info? I added an endpoint to PR #38 that will display the mappings for all collections. I tested the mappings by supplying them in the config file without commenting out `this.elasticManager.setMappings(collection);` and the mappings still seemed to be valid. Can you provide a more specific use case so that I can reproduce on my end? Thanks for letting us know about the issue you ran into!

**Comment by chrishearn** [comment]
Thanks for the quick response!

My use case for mappings is that my Mongo collections start with an uppercase letter but my ES types are all lowercase. My config file is as follows:

```
{
  "mongo": {
    "options": {
      "poolSize": 100
    },
    "url": "localhost:27017",
    "database": "omono-dev",
    "user": "dev",
    "password": "xxxxxx",
    "collections": ["Addresses", "Companies", "Contacts"]
  },
  "elasticsearch": {
    "host": "localhost:9200",
    "apiVersion": "5.5"
  },
  "bulkSize": 1000,
  "adminPort": 3333,
  "ignoreResumeTokensOnStart": false,
  "dumpOnStart": false,
  "resumeTokenInterval": 60000,
  "mappings": {
    "Addresses": {
      "index": "omono-dev",
      "type": "addresses"
    },
    "Companies": {
      "index": "omono-dev",
      "type": "companies"
    },
    "Contacts": {
      "index": "omono-dev",
      "type": "contacts",
      "parent": "companies",
      "parentId": "companyId"
    }
  },
  "logLevel": "info"
}
```

When I go to the new mapping endpoint you added it shows the following:

`{"default":{"index":"omono-dev","type":"$self"},"Addresses":{"index":"omono-dev","type":"Addresses"},"Companies":{"index":"omono-dev","type":"Companies"},"Contacts":{"index":"omono-dev","type":"Contacts","parent":"companies","parentId":"companyId"}}`

As you can see the type names appear in their original format with an uppercase first letter. It's as if the default mapping is taking precedence over the custom mappings I provided in the config.

If I change the index names on my custom mappings they are reflected correctly in the mappings endpoint, but regardless of what I change the 'type' properties to it still shows the original collection name.

I'm using node v8.11.2 on OSX 10.13.4 for some context on runtime environment.

**Comment by g2valdez** [comment]
I found the issue! It was a small typo on my behalf. It's addressed in [this commit](https://github.com/everyone-counts/mongo-stream/pull/38/commits/ca9e62255fec9ea896ea963e13696aac90c11a53). Thanks again for sharing the issue.
