### ISSUE TITLE
propose logo

### ISSUE THREAD

**Issue by dee-y** [everyone-counts/mongo-stream#47]
Hello @dfinlay @AndrewVDP @lordjabez  i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by dfinlay** [comment]
@dee-y Sounds good, I don't think we'll say no to you giving it a shot!

**Comment by dee-y** [comment]
Hello @dfinlay, i have come up with this design showing a mix of the mongo db logo and elastic search, representing the connection between the two working hand in hand as the project describes. If you do like the logo, do you pick the first or the second. Also if you have more ideas, further adjustments are welcomed. 

![mongostream-01](https://user-images.githubusercontent.com/36637989/42139191-cd5b9b94-7d80-11e8-9241-a64af2694c84.png)

**Comment by badavis** [comment]
These are great! We took a vote and #2 is our favorite.

**Comment by dee-y** [comment]
That's great!, i will have the logo in transparent png version along with different sizes and favicon version also, the editable versions of the logo will also be included along with the license for ownership sent to you in a PR soon.

Best regards,
Dee-y.

**Comment by dee-y** [comment]
Hi i have created a pull request here https://github.com/everyone-counts/mongo-stream/pull/50 containing logo files and editable PDF format, along with MIT license of ownership. Cheers!

You can contact me further anytime for future assistance,
Best regards,
Dee-y.
